### ISSUE TITLE
Ny logotyp

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/bin2023#1]
- [x] Se över den befintliga logotypen. Behövs en ny? Räcker det att förnya den gamla, eller är det bättre att göra en helt ny? Vad skall inspirationen till den nya vara, i så fall? 
- [x] Använd rätt färger. Oavsett om det blir en uppdatering eller en helt ny så skall logotypen följa ert valda färgtema. Se till att den fungerar även i svart/vitt samt att färgerna håller bra kontrast. 
- [x] Sikta på att supporta tre stolekar; favicon, fyrkantig avatar-storlek samt stor headerlogotype. Antingen kan designen fungera för alla tre, eller så får det tas fram mer och mindre komplexa varianter. Prototypa med wireframes. 
- [x] Bygg i Inkscape!
- [x] Användartester

**Comment by HermanLarsson** [comment]
![Image](https://user-images.githubusercontent.com/114070528/221858195-a6fba84d-d19d-4b7b-bfe5-b9143af2ab6a.svg)



![Image](https://user-images.githubusercontent.com/114070528/221858253-4ee64521-9008-44cc-ba9c-24331d3648ef.svg)



![Image](https://user-images.githubusercontent.com/114070528/221858282-8db9ed23-d025-409d-b5af-a73a3f3ea7ee.svg)

**Comment by HermanLarsson** [comment]
Klar
