### ISSUE TITLE
Sitemap av originalsidan

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/bin2023#10]
Analysera den befintliga webbsidan och gör en sitemap av den. Exempel på verktyg där detta är enkelt är Inkscape och Penpot.

**Comment by Hugo-Falk** [comment]
https://www.gloomaps.com/Mi7nWC9seV

**Comment by seetee** [comment]
Glöm inte att skapa en PR som "resolves #10" när ni är klara så denna issue löses.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
