### ISSUE TITLE
Planera användartester

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/bin2023#16]
Det går att både planera och genomföra användartester redan nu. 

* [Usabilit Testing: Don't Guess, Test.](https://www.uxbooth.com/articles/usability-testing-dont-guess-test/)     
* [How To Run Live User Testing](https://techcrunch.com/2014/02/18/how-to-run-live-user-testing-part-1-setup/?guccounter=1)   
* [What goes into a user testing script](https://boagworld.com/usability/what-goes-into-a-user-testing-script/)    
* [Testing design: How do you test a design comp?](https://boagworld.com/design/testing-design/)    

Testa wireframes med hjälp av online-verktyg. Skall ni använda eye-tracker när ni låter användare göra uppgifter? Skriv ett manus!

**Comment by Verafriberg** [comment]
Planera
– Vad ska testas?
– vilken data ska samlas in? Hur?
• Pilot-testa (testa testet!)
• Revidera
• Genomför test med deltagare
• Analysera resultat
• Rapportera resultat

**Comment by Verafriberg** [comment]
Ett användartest som inte tar för långt tid att göra. Det är en google form med simpla frågor!
https://docs.google.com/forms/d/e/1FAIpQLSepJ1jRGmj1SGBxf5vmQqKrfEHmTp8Vt2LGmnjF6V7T8MO7HA/viewform?usp=sf_link

**Comment by sofiefernlof** [comment]
https://www.toptal.com/designers/colorfilter
länk till hemsida för att kolla hur användarvänlig den är om man är färgblind.
