### ISSUE TITLE
Fonter

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/bin2023#3]
Analysera befintlig webbsida, se över konkurrenternas fontval och se vad trenderna just nu är (nya fonter, årets font, etc.). 

Se till att upphovsrätten efterlevs. Välj 1 eller som mest 2 fonter. Definiera vilken fontstorlek ([fluid type scale](https://www.fluid-type-scale.com/)) olika rubriker och brödtext skall ha.

**Comment by AlexanderSalomonsson** [comment]
Jag tänker att vi kan använda fonten som heter ((Gloock)) för rubriker och ((Poppins ))för articlar  och annat 



![Image](https://user-images.githubusercontent.com/102585782/220353725-fdd26c66-57ee-4e3d-822a-f7c52696985b.png)
![Image](https://user-images.githubusercontent.com/102585782/220353724-a2b411fa-6bbb-4808-80d5-075b3248375c.png)
