### ISSUE TITLE
Hitta stock-bilder

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/bin2023#4]
Analysera befintlig webbsida samt konkurrenter och fundera på vad för slags bildspråk som används. Leta upp stock-foton och samla så att de finns tillgängliga under projektet, både till moodboards, som exempelbilder men också som bakgrundsbilder och liknande. Se till att upphovsrätten efterlevs!

**Comment by Lajjaan** [comment]
_Uppdaterat innehåll_

**Comment by Lajjaan** [comment]
Bin och blomma:
> https://as2.ftcdn.net/v2/jpg/00/50/05/51/1000_F_50055160_t1bW3d9tFWwVtAKcJRiPX81P1FLz4VIn.jpg

> https://as1.ftcdn.net/v2/jpg/03/38/62/52/1000_F_338625213_M2u8cFkbvbGz8wEuy1DFUUj8SYmZ4AJH.jpg

Bibo:
> https://as1.ftcdn.net/v2/jpg/01/82/11/48/1000_F_182114823_ToxTtfEIVoFyMMBDHgfqzjMZyCaDwKiF.jpg

> https://t3.ftcdn.net/jpg/03/46/48/80/240_F_346488079_lrAVSUEmirDDZW10tmfgqi352WFdeTKG.jpg

> https://t3.ftcdn.net/jpg/00/43/82/58/240_F_43825860_6CrKN6S6eLscdOaTitSrO4xlTi60YcLU.jpg

> https://t3.ftcdn.net/jpg/04/57/68/68/240_F_457686857_VMFQ7vrT9duZsuHiMPMZUKD3h2jXtUNm.jpg

> https://t4.ftcdn.net/jpg/02/39/31/05/240_F_239310559_3NdqLmJT2oMHwbxFpXNOPdGDkTsnJkND.jpg

> https://t3.ftcdn.net/jpg/02/64/39/66/240_F_264396655_RbR231gjZzUSrWskgZQM1zaJxorOvy6C.jpg
