### ISSUE TITLE
Skapa moodboard

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/bin2023#6]
Analysera befintlig webbplats samt konkurrenter. Vad är syftet med sidan? Vilken känsla vill förmedlas? Skapa en moodboard, antingen fysiskt eller digitalt.

**Comment by sofiefernlof** [comment]
https://www.canva.com/design/DAFcgptLIpE/ckGbTDX56RlkD5MEKf8zmQ/view?utm_content=DAFcgptLIpE&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink
