### ISSUE TITLE
Skapa wireframes

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/bin2023#7]
Analysera innehållet på befintlig webbplats. Vilka sorters innehåll finns och hur skall det organiseras. Samråd med Data och de som arbetar med Content types / Taxonomies. Det behövs en wireframe för förstasidan samt en för varje content type. 

- [x] Wireframe för förstasidan 
- [x] Wireframe för varje content type

**Comment by HermanLarsson** [comment]
Desktop1: https://www.figma.com/file/p4p4R80OHvqQCMnA5LzZdY/wireframe1?node-id=0%3A1&t=ZaGDPb2Oze7OeuvS-1
Desktop2: https://www.figma.com/file/KiyDBbq6Qz9XDprvtEQ1z1/wireframe2?node-id=0%3A1&t=XdfdtAMPZNdqY2ps-1
Iphone14: https://www.figma.com/file/QiPXTRyQ8PWmgpMVgOuNul/wireframe3?node-id=0%3A1&t=Kvj8JWq1vQmuxKqX-1
